**NUMPY RANDOM PRACTICE**
---



In [3]:
import numpy as np


RANDOM AGE GENERATOR

In [4]:
ages=np.random.randint(18,60,10)
print(ages)

[24 18 40 59 25 23 45 52 22 19]


DICEROLLS

In [67]:
dice=np.random.randint(1,7,100)
print(dice)

[5 1 2 4 1 4 6 2 2 1 2 5 2 4 4 4 4 5 3 6 1 4 2 4 2 6 6 6 2 4 6 5 2 2 4 2 2
 6 4 6 6 4 1 6 5 5 2 5 2 1 4 4 4 5 1 5 5 1 1 1 1 4 3 3 1 3 3 1 3 5 2 2 1 4
 1 4 2 1 6 5 3 4 6 3 3 1 3 5 6 3 1 5 2 6 3 1 2 2 4 5]


MATRIX GENERATOR


*  np.random.rand(2,3)-positive floats
*  np.ranodm.randn(2,3)-neagative floats



In [ ]:
print(np.random.rand(2,3))

[[ 0.663217   -1.71230576  1.47067239]
 [ 0.61929024  2.37158592  2.03966219]]


CHOICE


*   It is used to select from the list




In [46]:
fruits=np.array(["apple","orange","pineapple"])
a=np.random.choice(fruits)
print(a)

apple


SEED


*  same output for every run



In [49]:
a=np.random.seed(42)
a=np.random.randint(1,7)
print(a)

4


SHUFFLE


*   shuffles the values of the list
*   return none as output if printed




In [63]:
a=np.array([1,2,3,4,5])
np.random.shuffle(a)
print(a)

[1 4 2 5 3]


PERMUTATION


*   Shuffles and create copy



In [66]:
a=np.array([1,2,3,4,5])
b=np.random.permutation(a)
print(b)

[2 4 5 3 1]


Practice -Lottery Number Picker

In [70]:
numbers=np.arange(1,50)
lottery=np.random.choice(numbers,6,replace=False)
print(lottery)

[13 16 38 34  7  8]


In [71]:
lottery = np.random.choice(range(1, 50), size=6, replace=False)
print(lottery)

[35 22 14 49  8 21]
