<a href="https://colab.research.google.com/github/belindacarolam04/numpy_learning/blob/main/Uniform.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

**USE OF UNIFORM**

Uniform-used for random decimal values

In [8]:
a=np.random.uniform(0,1,size=20)
print("Random 20 values between 0 and 1\n",a)

Random 20 values between 0 and 1
 [0.68819979 0.47288125 0.57697335 0.53156594 0.65765473 0.19447661
 0.3603608  0.34821858 0.49857288 0.36831154 0.56456182 0.71894844
 0.32500986 0.71205388 0.04650027 0.48930753 0.00710779 0.43648435
 0.03691071 0.38742517]


In [10]:
a=np.random.uniform(50,100,size=10)
print("Random values between 50 and 100\n",a)

Random values between 50 and 100
 [77.46043176 55.73439428 70.59432581 71.13565815 97.77945569 54.85186211
 89.85875357 96.40829769 86.60399473 81.48442844]


In [12]:
matr=np.random.uniform(size=(4,4))
print("4X4 Matrix:\n",matr)

4X4 Matrix:
 [[0.41749886 0.65821112 0.5050295  0.69619161]
 [0.56564183 0.1447219  0.61124667 0.27837821]
 [0.70468269 0.93098394 0.46060093 0.94199613]
 [0.90939241 0.44708857 0.90290219 0.79632027]]


PRACTICE-EMPLOYEE SALARY ANALYSER

In [3]:
salaries=np.random.uniform(20000,100000,size=20)
print("MAXIMUM SALARY:",np.max(salaries))
print("MINIMUM SALARY:",np.min(salaries))
print("AVERAGE SALARY:",np.mean(salaries))
print("EMPLOYEES ABOVE 80000:",salaries[salaries>80000])
print("EMPLOYEES BELOW 4000:",salaries[salaries<40000])

MAXIMUM SALARY: 97267.81222275033
MINIMUM SALARY: 26743.418949346138
AVERAGE SALARY: 66282.54448974403
EMPLOYEES ABOVE 80000: [83495.36248489 95249.63165902 93363.37319608 95204.80282877
 97267.81222275 83697.37735284 90506.73200428]
EMPLOYEES BELOW 4000: [36952.14591897 26778.15750348 26743.41894935]
